apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tekton-edit-binding
subjects:
- kind: ServiceAccount
  name: tekton-webhooks
  namespace: ystack
roleRef:
  kind: ClusterRole
  name: tekton-aggregate-edit
  apiGroup: rbac.authorization.k8s.io
